import {
  mdiAccountGroup,
  mdiAccountHeart,
  mdiAccountMultiple,
  mdiAccountSupervisor,
  mdiAirplaneTakeoff,
  mdiAlphabeticalVariant,
  mdiArrowLeftBold,
  mdiArrowRightBold,
  mdiBell,
  mdiBike,
  mdiBookOpenVariant,
  mdiBrush,
  mdiBullhorn,
  mdiCalendar,
  mdiCalendarTextOutline,
  mdiCamera,
  mdiCameraPlusOutline,
  mdiChevronRight,
  mdiChevronUp,
  mdiClockTimeFourOutline,
  mdiClose,
  mdiCogOutline,
  mdiCogs,
  mdiCommentMultiple,
  mdiCommentOutline,
  mdiCurrencyKrw,
  mdiDotsVertical,
  mdiEmoticonCryOutline,
  mdiFacebookMessenger,
  mdiHeart,
  mdiHeartOutline,
  mdiImage,
  mdiInformation,
  mdiKeyboardBackspace,
  mdiLogoutVariant,
  mdiMagnify,
  mdiMapMarker,
  mdiMenuDown,
  mdiMessageDraw,
  mdiMonitor,
  mdiMusicCircleOutline,
  mdiNoteTextOutline,
  mdiPartyPopper,
  mdiPencil,
  mdiPlus,
  mdiPower,
  mdiShareVariant,
  mdiThumbUpOutline,
  mdiWater,
  mdiWaterOutline,
} from '@mdi/js';

export const ICONS = {
  currencyKrw: mdiCurrencyKrw,
  twoPeople: mdiAccountMultiple,
  threePeople: mdiAccountGroup,
  mapMarker: mdiMapMarker,
  heart: mdiHeart,
  heartOut: mdiHeartOutline,
  search: mdiMagnify,
  back: mdiKeyboardBackspace,
  close: mdiClose,
  chevronRight: mdiChevronRight,
  chevronUp: mdiChevronUp,
  musicCircleOut: mdiMusicCircleOutline,
  thumbUpOut: mdiThumbUpOutline,
  arrowLeftBold: mdiArrowLeftBold,
  arrowRightBold: mdiArrowRightBold,
  commentOut: mdiCommentOutline,
  commentMultiple: mdiCommentMultiple,
  cameraOut: mdiCameraPlusOutline,
  camera: mdiCamera,
  menuDown: mdiMenuDown,
  plus: mdiPlus,
  airplaneTakeoff: mdiAirplaneTakeoff,
  bike: mdiBike,
  bookOpen: mdiBookOpenVariant,
  alphabetical: mdiAlphabeticalVariant,
  partyPopper: mdiPartyPopper,
  water: mdiWater,
  waterOut: mdiWaterOutline,
  power: mdiPower,
  facebookMessenger: mdiFacebookMessenger,
  cogs: mdiCogs,
  cogOut: mdiCogOutline,
  calendar: mdiCalendar,
  shareVariant: mdiShareVariant,
  cryOut: mdiEmoticonCryOutline,
  accountHeart: mdiAccountHeart,
  bell: mdiBell,
  brush: mdiBrush,
  messageDraw: mdiMessageDraw,
  bullhorn: mdiBullhorn,
  information: mdiInformation,
  logout: mdiLogoutVariant,
  pencil: mdiPencil,
  monitor: mdiMonitor,
  clock: mdiClockTimeFourOutline,
  supervisor: mdiAccountSupervisor,
  image: mdiImage,
  note: mdiNoteTextOutline,
  calendarOut: mdiCalendarTextOutline,
  dotsVertical: mdiDotsVertical,
};
