import {
    mdiAccountGroup,
    mdiAccountHeart,
    mdiAccountMultiple,
    mdiAirplaneTakeoff,
    mdiAlphabeticalVariant,
    mdiArrowLeftBold,
    mdiArrowRightBold,
    mdiBell,
    mdiBike,
    mdiBookOpenVariant,
    mdiBrush,
    mdiBullhorn,
    mdiCalendar,
    mdiCameraPlusOutline,
    mdiChevronRight,
    mdiChevronUp,
    mdiClockTimeFourOutline,
    mdiClose,
    mdiCogOutline,
    mdiCogs,
    mdiCommentMultiple,
    mdiCommentTextOutline,
    mdiCurrencyKrw,
    mdiEmoticonCryOutline,
    mdiFacebookMessenger,
    mdiHeart,
    mdiInformation,
    mdiKeyboardBackspace,
    mdiLogoutVariant,
    mdiMagnify,
    mdiMapMarker,
    mdiMenuDown,
    mdiMessageDraw,
    mdiMonitor,
    mdiMusicCircleOutline,
    mdiPartyPopper,
    mdiPencil,
    mdiPlus,
    mdiShareVariant,
    mdiThumbUpOutline,
    mdiWater,
    mdiWaterOutline,
} from '@mdi/js';

const ICONS = {
    currencyKrw: mdiCurrencyKrw,
    twoPeople: mdiAccountMultiple,
    threePeople: mdiAccountGroup,
    mapMarker: mdiMapMarker,
    heart: mdiHeart,
    search: mdiMagnify,
    back: mdiKeyboardBackspace,
    close: mdiClose,
    chevronRight: mdiChevronRight,
    chevronUp: mdiChevronUp,
    musicCircleOut: mdiMusicCircleOutline,
    thumbUpOut: mdiThumbUpOutline,
    arrowLeftBold: mdiArrowLeftBold,
    arrowRightBold: mdiArrowRightBold,
    commentOut: mdiCommentTextOutline,
    commentMultiple: mdiCommentMultiple,
    cameraOut: mdiCameraPlusOutline,
    menuDown: mdiMenuDown,
    plus: mdiPlus,
    airplaneTakeoff: mdiAirplaneTakeoff,
    bike: mdiBike,
    bookOpen: mdiBookOpenVariant,
    alphabetical: mdiAlphabeticalVariant,
    partyPopper: mdiPartyPopper,
    water: mdiWater,
    waterOut: mdiWaterOutline,
    facebookMessenger: mdiFacebookMessenger,
    cogs: mdiCogs,
    cogOut: mdiCogOutline,
    calendar: mdiCalendar,
    shareVariant: mdiShareVariant,
    cryOut: mdiEmoticonCryOutline,
    accountHeart: mdiAccountHeart,
    bell: mdiBell,
    brush: mdiBrush,
    messageDraw: mdiMessageDraw,
    bullhorn: mdiBullhorn,
    information: mdiInformation,
    logout: mdiLogoutVariant,
    pencil: mdiPencil,
    monitor: mdiMonitor,
    clock: mdiClockTimeFourOutline,
};

export {
    ICONS,
};
