const data = {
    data: {
        pageable: {
            pageNumber: 0,
        },
        content: [
            {
                groupDateText: '2021년 1월',
                meetings: [
                    {
                        isSameDayMeeting: true,
                        meetingDay: 10,
                        meetingDayOfWeek: '수요일',
                        seq: 8701,
                        title: '제 34회 정기 모임',
                        content: '23',
                        startDate: '2021년 2월 10일',
                        startTime: '12:00',
                        endDate: '2021년 2월 11일',
                        endTime: '13:00',
                        club: {
                            seq: 6327,
                            name: '테스트 18',
                            description: '123',
                            maximumNumber: 30,
                            userCount: 4,
                            mainImageUrl: '',
                        },
                        deleteFlag: false,
                        maximumNumber: 20,
                        regClubUser: {
                            seq: 6328,
                            user: {
                                seq: 7,
                                userRoles: [
                                    'ROLE_MEMBER',
                                ],
                                userName: '이동명',
                                birthday: null,
                                profileImageLink: '',
                            },
                            club: {
                                seq: 6327,
                                name: '테스트 18',
                                description: '123',
                                maximumNumber: 30,
                                userCount: 4,
                                mainImageUrl: '',
                            },
                            roles: [
                                {
                                    name: 'MASTER',
                                    roleGroupName: 'USER_TYPE',
                                },
                            ],
                        },
                        meetingApplications: [
                            {
                                seq: 8761,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:44:12',
                                updatedAt: '2021-02-08 00:44:12',
                                userInfo: {
                                    userSeq: 8747,
                                    userName: '맹공공',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8760,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:52',
                                updatedAt: '2021-02-08 00:43:52',
                                userInfo: {
                                    userSeq: 8737,
                                    userName: 'tae',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8759,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:37',
                                updatedAt: '2021-02-08 00:43:37',
                                userInfo: {
                                    userSeq: 8736,
                                    userName: '릴리',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8758,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:19',
                                updatedAt: '2021-02-08 00:43:19',
                                userInfo: {
                                    userSeq: 6419,
                                    userName: 'Lob',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8757,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:05',
                                updatedAt: '2021-02-08 00:43:05',
                                userInfo: {
                                    userSeq: 6347,
                                    userName: '꽑꽑이',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8756,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:42:37',
                                updatedAt: '2021-02-08 00:42:37',
                                userInfo: {
                                    userSeq: 6349,
                                    userName: 'TheWing',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8755,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:42:04',
                                updatedAt: '2021-02-08 00:42:04',
                                userInfo: {
                                    userSeq: 41,
                                    userName: '챙챙\uD83D\uDC97',
                                    profileImageLink: 'http://k.kakaocdn.net/dn/dRP7QZ/btqH4tS9S1f/DKWU0SVIdLvaOm6o4GRLG0/img_110x110.jpg',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8754,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:41:51',
                                updatedAt: '2021-02-08 00:41:51',
                                userInfo: {
                                    userSeq: 2,
                                    userName: '설동민',
                                    profileImageLink: 'http://k.kakaocdn.net/dn/bDkz1h/btqFoxKAIXH/Kj3d4mCLCAYkuF8wtegjk0/img_110x110.jpg',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8753,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:41:38',
                                updatedAt: '2021-02-08 00:41:38',
                                userInfo: {
                                    userSeq: 1,
                                    userName: '정준_Eric',
                                    profileImageLink: 'http://k.kakaocdn.net/dn/ecIC9x/btqImebhdbp/9yeRhMlndDKyKUB88DIIOk/p1.jpg',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8752,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:40:22',
                                updatedAt: '2021-02-08 00:40:22',
                                userInfo: {
                                    userSeq: 7,
                                    userName: '이동명',
                                    profileImageLink: '',
                                    regUserFlag: true,
                                },
                            },
                        ],
                        isCurrentUserRegMeeting: true,
                        isCurrentUserApplicationMeeting: true,
                        region: '강남역 2번 출구',
                        regionURL: null,
                        cost: 10000,
                        isOpen: true,
                    },
                    {
                        isSameDayMeeting: false,
                        meetingDay: 2,
                        meetingDayOfWeek: '화요일',
                        seq: 8471,
                        title: '벙개 스터디 일정',
                        content: '213',
                        startDate: '2021년 2월 10일',
                        startTime: '12:00',
                        endDate: '2021년 2월 11일',
                        endTime: '13:00',
                        club: {
                            seq: 6327,
                            name: '테스트 18',
                            description: '123',
                            maximumNumber: 30,
                            userCount: 4,
                            mainImageUrl: '',
                        },
                        deleteFlag: false,
                        maximumNumber: 20,
                        regClubUser: {
                            seq: 6328,
                            user: {
                                seq: 7,
                                userRoles: [
                                    'ROLE_MEMBER',
                                ],
                                userName: '이동명',
                                birthday: null,
                                profileImageLink: '',
                            },
                            club: {
                                seq: 6327,
                                name: '테스트 18',
                                description: '123',
                                maximumNumber: 30,
                                userCount: 4,
                                mainImageUrl: '',
                            },
                            roles: [
                                {
                                    name: 'MASTER',
                                    roleGroupName: 'USER_TYPE',
                                },
                            ],
                        },
                        meetingApplications: [
                            {
                                seq: 8761,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:44:12',
                                updatedAt: '2021-02-08 00:44:12',
                                userInfo: {
                                    userSeq: 8747,
                                    userName: '맹공공',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8760,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:52',
                                updatedAt: '2021-02-08 00:43:52',
                                userInfo: {
                                    userSeq: 8737,
                                    userName: 'tae',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                            {
                                seq: 8759,
                                deleteFlag: false,
                                createdAt: '2021-02-08 00:43:37',
                                updatedAt: '2021-02-08 00:43:37',
                                userInfo: {
                                    userSeq: 8736,
                                    userName: '릴리',
                                    profileImageLink: '',
                                    regUserFlag: false,
                                },
                            },
                        ],
                        isCurrentUserRegMeeting: false,
                        isCurrentUserApplicationMeeting: false,
                        region: '홍대 스타벅스',
                        regionURL: null,
                        cost: 5000,
                        isOpen: true,
                    },
                    {
                        isSameDayMeeting: false,
                        meetingDay: 1,
                        meetingDayOfWeek: '월요일',
                        seq: 8401,
                        title: '판교 점심 모임',
                        content: '23',
                        startDate: '2021년 2월 10일',
                        startTime: '12:00',
                        endDate: '2021년 2월 11일',
                        endTime: '13:00',
                        club: {
                            seq: 6327,
                            name: '테스트 18',
                            description: '123',
                            maximumNumber: 30,
                            userCount: 4,
                            mainImageUrl: '',
                        },
                        deleteFlag: false,
                        maximumNumber: null,
                        regClubUser: {
                            seq: 6328,
                            user: {
                                seq: 7,
                                userRoles: [
                                    'ROLE_MEMBER',
                                ],
                                userName: '이동명',
                                birthday: null,
                                profileImageLink: '',
                            },
                            club: {
                                seq: 6327,
                                name: '테스트 18',
                                description: '123',
                                maximumNumber: 30,
                                userCount: 4,
                                mainImageUrl: '',
                            },
                            roles: [
                                {
                                    name: 'MASTER',
                                    roleGroupName: 'USER_TYPE',
                                },
                            ],
                        },
                        meetingApplications: [
                            {
                                seq: 8521,
                                deleteFlag: false,
                                createdAt: '2021-01-10 02:20:33',
                                updatedAt: '2021-01-10 02:20:33',
                                userInfo: {
                                    userSeq: 1,
                                    userName: '정준_Eric',
                                    profileImageLink: 'http://k.kakaocdn.net/dn/ecIC9x/btqImebhdbp/9yeRhMlndDKyKUB88DIIOk/p1.jpg',
                                    regUserFlag: false,
                                },
                            },
                        ],
                        isCurrentUserRegMeeting: true,
                        isCurrentUserApplicationMeeting: false,
                        region: '판교 H스퀘어 S동',
                        regionURL: null,
                        cost: 5000,
                        isOpen: false,
                    },
                ],
            },
            {
                groupDateText: '2020년 12월',
                meetings: [
                    {
                        isSameDayMeeting: true,
                        meetingDay: 24,
                        meetingDayOfWeek: '월요일',
                        seq: 84011,
                        title: '제 33회 정기 모임',
                        content: '23',
                        startDate: '2021년 2월 10일',
                        startTime: '12:00',
                        endDate: '2021년 2월 11일',
                        endTime: '13:00',
                        club: {
                            seq: 6327,
                            name: '테스트 18',
                            description: '123',
                            maximumNumber: 30,
                            userCount: 4,
                            mainImageUrl: '',
                        },
                        deleteFlag: false,
                        maximumNumber: null,
                        regClubUser: {
                            seq: 6328,
                            user: {
                                seq: 7,
                                userRoles: [
                                    'ROLE_MEMBER',
                                ],
                                userName: '이동명',
                                birthday: null,
                                profileImageLink: '',
                            },
                            club: {
                                seq: 6327,
                                name: '테스트 18',
                                description: '123',
                                maximumNumber: 30,
                                userCount: 4,
                                mainImageUrl: '',
                            },
                            roles: [
                                {
                                    name: 'MASTER',
                                    roleGroupName: 'USER_TYPE',
                                },
                            ],
                        },
                        meetingApplications: [
                            {
                                seq: 8521,
                                deleteFlag: false,
                                createdAt: '2021-01-10 02:20:33',
                                updatedAt: '2021-01-10 02:20:33',
                                userInfo: {
                                    userSeq: 1,
                                    userName: '정준_Eric',
                                    profileImageLink: 'http://k.kakaocdn.net/dn/ecIC9x/btqImebhdbp/9yeRhMlndDKyKUB88DIIOk/p1.jpg',
                                    regUserFlag: false,
                                },
                            },
                        ],
                        isCurrentUserRegMeeting: true,
                        isCurrentUserApplicationMeeting: false,
                        region: '강남역 2번 출구',
                        regionURL: null,
                        cost: 5000,
                        isOpen: false,
                    },
                ],
            },
        ],
        last: true,
        size: 20,
        totalPages: 1,
    },
    message: 'success',
};

function getMeetings() {
    return new Promise((resolve) => resolve({ data }));
}

export { getMeetings };
