name: '[Deploy] AWS EC2 - nginx'

on:
  workflow_dispatch:

jobs:
  upload_to_ec2_nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: tar-build-output
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              tar -zcvf build.tar.gz ./dist

      - name: Deploy to nginx-server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          PORT: 22
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./build.tar.gz"
          target: "./config-frontend/temp"
          strip_components: 3

      - name: Launch Script in Remote Server
        if: ${{ success() }}
        uses: fifsky/ssh-action@master
        with:
          command: |
            sh ~/config-frontend/deploy-to-nginx.sh
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          args: "-tt"
